# https://taskfile.dev

version: '3'

tasks:
  search:*:
    vars:
      DATASET_ID: "{{index .MATCH 0}}"
    cmds:
      - uv run ktrainer search --dims 3 --mode raw --algorithm evolutionary --metric CKA --generations 10 --chain-size 12 --mutpb 0.05 --cxpb 0.5 --out-path ./results/{{.DATASET_ID}} {{.CLI_ARGS}}

  generate:*:
    vars:
      DATASET_ID: "{{index .MATCH 0}}"
    cmds:
      - uv run ktrainer generate --out-path data --dataset-id {{.DATASET_ID}} {{.CLI_ARGS}}
