# https://taskfile.dev

version: '3'

tasks:
  search:
    cmds:
      - uv run ktrainer search --dims 3 --mode raw --algorithm evolutionary --metric CKA --mutpb 0.05 --cxpb 0.5 --out-path ./results/{{.DATASET_ID}} {{.CLI_ARGS}}

  generate:*:
    vars:
      DATASET_ID: "{{index .MATCH 0}}"
    cmds:
      - uv run ktrainer generate --out-path data --dataset-id {{.DATASET_ID}} {{.CLI_ARGS}}

  benchmark:
    cmds:
      - uv run ktrainer benchmark {{.CLI_ARGS}}

  compact:
    cmds:
      - uv run ktrainer compact {{.CLI_ARGS}}

  # Sky
  launch:
    cmds:
      - uv run sky jobs launch {{.CLI_ARGS}}

  cost:
    cmds:
      - uv run sky cost-report -a

  job-logs:*:
    vars:
      JOB_ID: "{{index .MATCH 0}}"
    cmds:
      - uv run sky jobs logs {{.JOB_ID}}

  cancel-job:*:
    vars:
      JOB_ID: "{{index .MATCH 0}}"
    cmds:
      - uv run sky jobs cancel {{.JOB_ID}}