# https://taskfile.dev

version: '3'

tasks:
  train:*:
    vars:
      DATASET_ID: "{{index .MATCH 0}}"
    cmds:
      - pdm run ktrainer search --file-path ./data/{{.DATASET_ID}}_3d_200s_0.5ir_4321_2025-08-10.csv --dims 3 --mode raw --algorithm evolutionary --metric CKA --generations 100 --population 1000 --chain-size 12 --mutpb 0.05 --cxpb 0.5 --processes 12 --out-path ./results/{{.DATASET_ID}}
